### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by paternal** [uktug/uk-tex-faq#7] opened 2018-06-13 09:30 UTC
The website https://www.tex.ac.uk/ is unreachable (I get a github 404 page). This looks like a error in the github pages configuration.

**Comment by josephwright** [comment] 2018-06-13 09:47
We know :)
There are some behind-the-scenes technical issues with the older address. In the end we'll sort them, but they depend on getting action by third parties (DNS) so I can't promise a timeframe just yet.

Note that longer-term the rules for `.ac.uk` URLs have been tightened up: we can't be sure that we'll hold on to `tex.ac.uk` 'for ever'.

**Comment by josephwright** [comment] 2018-06-13 09:50
Duplicate of https://github.com/texfaq/historical/issues/1

**Comment by paternal** [comment] 2018-06-13 09:50
Ok. Thanks!

**Closed by josephwright** 2018-06-13 09:50 UTC
Labels: bug, duplicate
